name: finzoo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  google_fonts: ^8.2.1
  shared_preferences: ^2.5.5
  video_player: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro_icons/
    - assets/images/book_icons/
    - assets/images/goals/
    - assets/images/house_inv/
    - assets/images/house_inv_clothes/
    - assets/images/house_inv_shower/
    - assets/images/wardrobe/
    - assets/videos/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FEFCF4"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#FEFCF4"
    image: assets/images/splash_logo.png
    icon_background_color: "#FEFCF4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  adaptive_icon_background: "#FFFAEE"
  adaptive_icon_foreground: assets/images/app_icon.png
  remove_alpha_ios: true
  background_color_ios: "#FFFAEE"
